
module.exports = {

  STANDARD: {
    SEER: 'SEER',
    VILLAGER: 'VILLAGER',
    WEREWOLF: 'WEREWOLF'
  },
  COMPLEX_WOLVES: {
    MINION: 'MINION',
    WOLFMAN: 'WOLFMAN'
  },
  COMPLEX_VILLAGER: {
    TANNER: 'TANNER',
    BEHOLDER: 'BEHOLDER',
    BODYGUARD: 'BODYGUARD',
    TOUGH_GUY: 'TOUGH_GUY',
    INSOMNIAC: 'INSOMNIAC',
    PACIFIST: 'PACIFIST',
    LYCAN: 'LYCAN'
  }

};